### ISSUE TITLE
Add checksum to images?

### ISSUE THREAD

**Issue by kevinyamauchi** [czbiohub/imagingDB#37]
What are your thoughts on adding some sort of checksum to the image metadata so we can verify that images are downloaded correctly?

**Comment by jennyfolkesson** [comment]
I think that would be a very good idea.
Adding a hash to the metadata is trivial, what will require some thought is updating the database with checksums of already uploaded datasets. But I guess I'll have to learn how to do database migrations at some point anyway...

**Comment by kevinyamauchi** [comment]
Hey, @jennyfolkesson! I'm pretty interested in adding image checksums to our images to our in situ transcriptomics workflow. Do you think the best approach is to make this a required field and migrate the DB (as you suggested) or just add a key to the jsonb with a hash of the image (e.g., SHA-256)? Or something else?

**Comment by jennyfolkesson** [comment]
Adding it to the jsonb would definitely be easier, but it might be nice to do it for all datasets, and then maybe we should "do it right" with a database migration and a required field.
You probably want checksums for already uploaded data too, right? If so we can't avoid a database migration anyway...
How do you want to distribute the workload? E.g. I can look into how to easiest do the migration if you would like to update imagingDB?

**Comment by jennyfolkesson** [comment]
Sure! I'm free pretty much all day Friday.

**Comment by kevinyamauchi** [comment]
Hey, @jennyfolkesson. Looking forward to our meeting today! Just so we're on the same page, this is my plan for updating the DB to support a hash:

__Uploading__
*  Add a hash column (`sha-256`) to the `Frames` class
* Add the hash function to `meta_utils` (this way it's easily changed/exchanged)
* Add a hash property (list) to the `FileSplitter` base class
* Add a hash method to the (operates on `self.im_stack`). This method will call the hash function in `meta_utils`
* Add input argument for the `hash_list` to `insert_frames()` in `db_session.py` and add it to the instantiation of `Frames`
* Update `data_uploader.py` to include the `hash_list` in `db_inst.insert_frames` (get from the hash property added to the `FileSplitter` base class)

__Downloading__
I am not sure we need to add a check to the downloader CLI. Perhaps we can add a function in utils to verify a set of images against a metadata file. What do you think?

**Comment by jennyfolkesson** [comment]
That looks very much like I had imagined it.
As you say, I don't think we need to validate each image that gets downloaded, but we can provide a standalone script that will validate images against the sha-256 metadata field for you if you so wish.

**Comment by kevinyamauchi** [comment]
@jennyfolkesson, do you think we should calculate the hash on the numpy array or the png that is uploaded to S3? I'm leaning towards the numpy array of the images because it's the actual image data and it's more straightforward to add, but I'm happy to go the other way if you have a strong preference.

**Comment by jennyfolkesson** [comment]
I think it makes sense to hash the array for each frame like you say. It's the actual data and not dependent on what compression we use.
