### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by kevinyamauchi** [czbiohub/imagingDB#47]
Per the discussion in #46 , we should add continuous integration testing.

**Comment by jennyfolkesson** [comment]
There are some issues running travis with moto, which don't seem to be resolved yet:
https://github.com/spulec/moto/issues/1796

**Comment by jennyfolkesson** [comment]
Actually, it looks like it's working now - it was the testing of the abstract class file_splitter that caused all the issues.
For now I've removed those tests in https://github.com/czbiohub/imagingDB/pull/50
Once I've found a way to combine abstract class testing with moto + travis I'll add them back.

**Comment by jennyfolkesson** [comment]
Travis CI is added to repo.
